// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Instance struct {
	ID              pgtype.UUID
	Name            string
	Status          string
	PhoneNumber     pgtype.Text
	TagID           pgtype.Text
	IgnoreGroups    pgtype.Bool
	WebhookUrl      pgtype.Text
	ReceiveMessages pgtype.Bool
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type Tag struct {
	ID        pgtype.UUID
	Name      string
	Color     string
	CreatedAt pgtype.Timestamp
}

type WhatsmeowAppStateSyncKey struct {
	OurJid      string
	KeyID       []byte
	KeyData     []byte
	Timestamp   int64
	Fingerprint []byte
}

type WhatsmeowAppStateVersion struct {
	OurJid  string
	Name    string
	Version int64
	Hash    []byte
}

type WhatsmeowChatSetting struct {
	OurJid     string
	ChatJid    string
	MutedUntil int64
	Pinned     bool
	Archived   bool
}

type WhatsmeowContact struct {
	OurJid       string
	TheirJid     string
	FirstName    string
	FullName     string
	PushName     string
	BusinessName string
	RowID        int64
}

type WhatsmeowDevice struct {
	Jid              string
	RegistrationID   int32
	NoiseKey         []byte
	IdentityKey      []byte
	SignedPreKeyID   int32
	SignedPreKey     []byte
	SignedPreKeySig  []byte
	AdvKeySecret     []byte
	AdvKeyIndex      int32
	AdvAccountSig    []byte
	Platform         string
	BusinessName     string
	PushName         string
	AdAccountID      string
	VerifiedName     []byte
	VerifiedNameCert []byte
	VerifiedNameVer  []byte
	PairProtoVersion int32
}

type WhatsmeowIdentityKey struct {
	OurJid   string
	TheirJid string
	Content  []byte
}

type WhatsmeowPreKey struct {
	OurJid     string
	KeyID      int32
	Content    []byte
	UploadTime int64
	Uploaded   bool
}

type WhatsmeowSenderKey struct {
	OurJid   string
	GroupID  string
	SenderID string
	Content  []byte
}

type WhatsmeowSession struct {
	OurJid   string
	TheirJid string
	Content  []byte
}
