// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Instance struct {
	ID              pgtype.UUID
	Name            string
	Status          string
	PhoneNumber     pgtype.Text
	TagID           pgtype.Text
	IgnoreGroups    pgtype.Bool
	WebhookUrl      pgtype.Text
	ReceiveMessages pgtype.Bool
	ProxyEnabled    pgtype.Bool
	ProxyUrl        pgtype.Text
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type Tag struct {
	ID        pgtype.UUID
	Name      string
	Color     string
	CreatedAt pgtype.Timestamp
}
