// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (
    name, webhook_url, tag_id, ignore_groups, receive_messages, proxy_enabled, proxy_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, status, phone_number, tag_id, ignore_groups, webhook_url, receive_messages, proxy_enabled, proxy_url, created_at, updated_at
`

type CreateInstanceParams struct {
	Name            string
	WebhookUrl      pgtype.Text
	TagID           pgtype.Text
	IgnoreGroups    pgtype.Bool
	ReceiveMessages pgtype.Bool
	ProxyEnabled    pgtype.Bool
	ProxyUrl        pgtype.Text
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.Name,
		arg.WebhookUrl,
		arg.TagID,
		arg.IgnoreGroups,
		arg.ReceiveMessages,
		arg.ProxyEnabled,
		arg.ProxyUrl,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.PhoneNumber,
		&i.TagID,
		&i.IgnoreGroups,
		&i.WebhookUrl,
		&i.ReceiveMessages,
		&i.ProxyEnabled,
		&i.ProxyUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
    name, color
) VALUES (
    $1, $2
)
RETURNING id, name, color, created_at
`

type CreateTagParams struct {
	Name  string
	Color string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instances
WHERE id = $1
`

func (q *Queries) DeleteInstance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInstance, id)
	return err
}

const deleteInstanceByName = `-- name: DeleteInstanceByName :exec
DELETE FROM instances
WHERE name = $1
`

func (q *Queries) DeleteInstanceByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteInstanceByName, name)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT id, name, status, phone_number, tag_id, ignore_groups, webhook_url, receive_messages, proxy_enabled, proxy_url, created_at, updated_at FROM instances
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInstance(ctx context.Context, id pgtype.UUID) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.PhoneNumber,
		&i.TagID,
		&i.IgnoreGroups,
		&i.WebhookUrl,
		&i.ReceiveMessages,
		&i.ProxyEnabled,
		&i.ProxyUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceByName = `-- name: GetInstanceByName :one
SELECT id, name, status, phone_number, tag_id, ignore_groups, webhook_url, receive_messages, proxy_enabled, proxy_url, created_at, updated_at FROM instances
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetInstanceByName(ctx context.Context, name string) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceByName, name)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.PhoneNumber,
		&i.TagID,
		&i.IgnoreGroups,
		&i.WebhookUrl,
		&i.ReceiveMessages,
		&i.ProxyEnabled,
		&i.ProxyUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceByPhoneNumber = `-- name: GetInstanceByPhoneNumber :one
SELECT id, name, status, phone_number, tag_id, ignore_groups, webhook_url, receive_messages, proxy_enabled, proxy_url, created_at, updated_at FROM instances
WHERE phone_number = $1 AND status = 'connected' LIMIT 1
`

func (q *Queries) GetInstanceByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) (Instance, error) {
	row := q.db.QueryRow(ctx, getInstanceByPhoneNumber, phoneNumber)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.PhoneNumber,
		&i.TagID,
		&i.IgnoreGroups,
		&i.WebhookUrl,
		&i.ReceiveMessages,
		&i.ProxyEnabled,
		&i.ProxyUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, name, color, created_at FROM tags
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listConnectedInstances = `-- name: ListConnectedInstances :many
SELECT id, name, status, phone_number, tag_id, ignore_groups, webhook_url, receive_messages, proxy_enabled, proxy_url, created_at, updated_at FROM instances
WHERE status = 'connected'
`

func (q *Queries) ListConnectedInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listConnectedInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.PhoneNumber,
			&i.TagID,
			&i.IgnoreGroups,
			&i.WebhookUrl,
			&i.ReceiveMessages,
			&i.ProxyEnabled,
			&i.ProxyUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstances = `-- name: ListInstances :many
SELECT id, name, status, phone_number, tag_id, ignore_groups, webhook_url, receive_messages, proxy_enabled, proxy_url, created_at, updated_at FROM instances
ORDER BY created_at DESC
`

func (q *Queries) ListInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.Query(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.PhoneNumber,
			&i.TagID,
			&i.IgnoreGroups,
			&i.WebhookUrl,
			&i.ReceiveMessages,
			&i.ProxyEnabled,
			&i.ProxyUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, color, created_at FROM tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstanceSettings = `-- name: UpdateInstanceSettings :one
UPDATE instances
SET webhook_url = $2, ignore_groups = $3, receive_messages = $4, tag_id = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, phone_number, tag_id, ignore_groups, webhook_url, receive_messages, proxy_enabled, proxy_url, created_at, updated_at
`

type UpdateInstanceSettingsParams struct {
	ID              pgtype.UUID
	WebhookUrl      pgtype.Text
	IgnoreGroups    pgtype.Bool
	ReceiveMessages pgtype.Bool
	TagID           pgtype.Text
}

func (q *Queries) UpdateInstanceSettings(ctx context.Context, arg UpdateInstanceSettingsParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstanceSettings,
		arg.ID,
		arg.WebhookUrl,
		arg.IgnoreGroups,
		arg.ReceiveMessages,
		arg.TagID,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.PhoneNumber,
		&i.TagID,
		&i.IgnoreGroups,
		&i.WebhookUrl,
		&i.ReceiveMessages,
		&i.ProxyEnabled,
		&i.ProxyUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstanceSettingsByName = `-- name: UpdateInstanceSettingsByName :one
UPDATE instances
SET webhook_url = $2, ignore_groups = $3, receive_messages = $4, tag_id = $5, proxy_enabled = $6, proxy_url = $7, updated_at = NOW()
WHERE name = $1
RETURNING id, name, status, phone_number, tag_id, ignore_groups, webhook_url, receive_messages, proxy_enabled, proxy_url, created_at, updated_at
`

type UpdateInstanceSettingsByNameParams struct {
	Name            string
	WebhookUrl      pgtype.Text
	IgnoreGroups    pgtype.Bool
	ReceiveMessages pgtype.Bool
	TagID           pgtype.Text
	ProxyEnabled    pgtype.Bool
	ProxyUrl        pgtype.Text
}

func (q *Queries) UpdateInstanceSettingsByName(ctx context.Context, arg UpdateInstanceSettingsByNameParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstanceSettingsByName,
		arg.Name,
		arg.WebhookUrl,
		arg.IgnoreGroups,
		arg.ReceiveMessages,
		arg.TagID,
		arg.ProxyEnabled,
		arg.ProxyUrl,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.PhoneNumber,
		&i.TagID,
		&i.IgnoreGroups,
		&i.WebhookUrl,
		&i.ReceiveMessages,
		&i.ProxyEnabled,
		&i.ProxyUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :one
UPDATE instances
SET status = $2, phone_number = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, phone_number, tag_id, ignore_groups, webhook_url, receive_messages, proxy_enabled, proxy_url, created_at, updated_at
`

type UpdateInstanceStatusParams struct {
	ID          pgtype.UUID
	Status      string
	PhoneNumber pgtype.Text
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstanceStatus, arg.ID, arg.Status, arg.PhoneNumber)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.PhoneNumber,
		&i.TagID,
		&i.IgnoreGroups,
		&i.WebhookUrl,
		&i.ReceiveMessages,
		&i.ProxyEnabled,
		&i.ProxyUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstanceStatusByName = `-- name: UpdateInstanceStatusByName :one
UPDATE instances
SET status = $2, phone_number = $3, updated_at = NOW()
WHERE name = $1
RETURNING id, name, status, phone_number, tag_id, ignore_groups, webhook_url, receive_messages, proxy_enabled, proxy_url, created_at, updated_at
`

type UpdateInstanceStatusByNameParams struct {
	Name        string
	Status      string
	PhoneNumber pgtype.Text
}

func (q *Queries) UpdateInstanceStatusByName(ctx context.Context, arg UpdateInstanceStatusByNameParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstanceStatusByName, arg.Name, arg.Status, arg.PhoneNumber)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.PhoneNumber,
		&i.TagID,
		&i.IgnoreGroups,
		&i.WebhookUrl,
		&i.ReceiveMessages,
		&i.ProxyEnabled,
		&i.ProxyUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = $2, color = $3
WHERE id = $1
RETURNING id, name, color, created_at
`

type UpdateTagParams struct {
	ID    pgtype.UUID
	Name  string
	Color string
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
